version: 2.1

orbs: 
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:latest
    resource_class: medium # ここで指定

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install   # npmパッケージインストール
      - run: npm run build  # ソースビルド実行
      - run: "echo Hello, World!"
      - run: ls -la
      - run: pwd
      - persist_to_workspace:
          root: .
          paths: [ '*' ]

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace: 
          at: .
      - aws-s3/sync: 
          from: ./public
          overwrite: true
          to: 's3://circle-ci-test-20220624'
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
