version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    resource_class: medium # ここで指定

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install   # npmパッケージインストール
      - run: npm run build  # ソースビルド実行
      - run: "echo Hello, World!"
      - run: ls -la
      - persist_to_workspace:
          root: .
          paths: [ '*' ]
  deploy:
    steps:
      - run: ls -la
  #   environment:
  #     - AWS_S3_BUCKET_NAME: 【自分のS3バケット名】
    docker:
      - image: innovatorjapan/awscli:latest
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run: aws s3 sync . s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete --exclude=".git/*" --exclude=".circleci/*" --exclude="node_modules/*"  # ここのexcludeオプションは自分の環境に合わせる

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
