version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:latest
    resource_class: medium # ここで指定

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install   # npmパッケージインストール
      - run: npm run build  # ソースビルド実行
      - run: "echo Hello, World!"
      - run: ls -la
      - run: pwd
      - persist_to_workspace:
          root: .
          paths: [ '*' ]
  deploy:
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: ls -la
      - run: pwd
      - aws-s3/sync:
          from: public
          to: s3://circle-ci-test-20220624
          overwrite: true
    docker:
      - image: circleci/node:latest
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
